services:
  # Backend Service (Node.js)
  - type: web
    name: renomeador-nf-gdm-backend
    env: node
    region: oregon
    plan: free
    healthCheckPath: /
    # Define o diretório de trabalho para o backend
    cwd: ./server
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "18.17.1" # Usando uma versão LTS estável

  # Frontend Service (React Static Site)
  - type: static_site
    name: renomeador-nf-gdm-frontend
    region: oregon
    plan: free
    # Comando de build explícito para o frontend
    buildCommand: "cd renomeador-nf-gdm-app && npm install && npm run build"
    # O diretório onde o resultado do build estará
    staticPublishPath: ./renomeador-nf-gdm-app/build
    envVars:
      - key: NODE_VERSION
        value: "18.17.1"
