services:
  - type: web
    name: renomeador-nf-gdm-backend
    env: node
    region: oregon
    plan: free
    healthCheckPath: /
    buildCommand: "npm install"
    startCommand: "npm start"
    cwd: server
    envVars:
      - key: NODE_VERSION
        value: 18.0.0

  - type: web
    name: renomeador-nf-gdm-frontend
    env: static
    region: oregon
    plan: free
    staticPublishPath: renomeador-nf-gdm-app/build
    buildCommand: "npm run build"
    envVars:
      - key: NODE_VERSION
        value: 18.0.0